spring.application.name=hotel-itc

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_info
spring.datasource.username=root
spring.datasource.password=ashu1225
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.session.jdbc.initialize-schema=always


spring.mvc.hiddenmethod.filter.enabled=true